### ISSUE TITLE
Feature Request: Add WhatsApp Contact Button

### ISSUE THREAD

**Issue by Swiftmetals** [Swiftmetals/website#3]
**Description**: We would like to enhance customer communication by adding a WhatsApp contact button to the SwiftMetals website. This will allow users to easily reach out for inquiries or support.

### Requirements:

_The button should be prominently displayed on the homepage and contact page.
It should link to our official WhatsApp number.
Additional Information:_

**Consider using the WhatsApp API for seamless integration.**

**Comment by AKASHYADAVO** [comment]
Hi, I would like to work on this issue of adding a WhatsApp contact button to the SwiftMetals website to improve customer communication. I have a clear plan for implementing the feature using the WhatsApp API and ensuring it fits seamlessly with the website's design.

Could you please assign this issue to me? I’ll provide regular updates and ensure timely completion.

Thank you!

**Comment by AKASHYADAVO** [comment]
HI, CAN I TAKE MORE THAN ONE ISSUE AT  TIME

**Comment by Swiftmetals** [comment]
Yes, you can, but please complete this assigned issue first. Once it's reviewed, you can proceed with the next task
